site_name: CourtVision
site_description: CourtVision is library and appication that extracts useful information from videos of court-based games
site_url: https://zizu.co.za/
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: motion_blur_FILL0_wght400_GRAD0_opsz48.png
  favicon: motion_blur_FILL0_wght400_GRAD0_opsz48.png
  language: en
repo_name: benjamindev/courtvision
repo_url: https://github.com/benjamindev/courtvision
edit_uri: ''
markdown_extensions:
  - footnotes
plugins:
- search
- mkdocstrings

# - markdownextradata:
    # data: data
nav:
- API Documentation:
    - 'courtvision.vis': api/vision.md
    - 'courtvision.geometry': api/geometry.md
