[tool.poetry]
name = "courtvision"
version = "0.1.0"
description = ""
authors = ["benjamin <benjamin@thinkst.com>"]
license = "MIT"
readme = "README.md"
[tool.poetry.dependencies]
python = "^3.10"
imageio = "^2.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
